import type { CleaningRecord } from '../types/cleaning';

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

function daysFrom(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString();
}

export const CLEANING_DUMMY_DATA: CleaningRecord[] = [
  {
    id: 'RVS-A',
    machineName: 'RVS A',
    machineType: 'RVS',
    subLabel: 'Filing - Lt1',
    location: 'Lantai 1',
    lastCleaned: daysAgo(28),
    nextCleaning: daysFrom(7),
    checklistStatus: null,
    status: 'overdue',
    hasRecord: true,
    reportApproved: false,
  },
  {
    id: 'RVS-B',
    machineName: 'RVS B',
    machineType: 'RVS',
    subLabel: 'Filing - Lt1',
    location: 'Lantai 1',
    lastCleaned: daysAgo(20),
    nextCleaning: daysFrom(15),
    checklistStatus: 'approved',
    status: 'safe',
    hasRecord: true,
    reportApproved: true,
  },
  {
    id: 'TOYO-LT1',
    machineName: 'TOYO',
    machineType: 'TOYO',
    subLabel: 'Filing - Lt1',
    location: 'Lantai 1',
    lastCleaned: daysAgo(5),
    nextCleaning: daysFrom(30),
    checklistStatus: 'approved',
    status: 'safe',
    hasRecord: true,
    reportApproved: true,
  },
  {
    id: 'WB-1',
    machineName: 'WB 1',
    machineType: 'WB',
    subLabel: 'Compounding - Lt4',
    location: 'Lantai 4',
    lastCleaned: daysAgo(4),
    nextCleaning: daysFrom(3),
    checklistStatus: null,
    status: 'overdue',
    hasRecord: false,
    reportApproved: false,
  },
  {
    id: 'WB-2',
    machineName: 'WB 2',
    machineType: 'WB',
    subLabel: 'Compounding - Lt4',
    location: 'Lantai 4',
    lastCleaned: daysAgo(4),
    nextCleaning: daysFrom(3),
    checklistStatus: null,
    status: 'overdue',
    hasRecord: false,
    reportApproved: false,
  },
  {
    id: 'WB-3',
    machineName: 'WB 3',
    machineType: 'WB',
    subLabel: 'Compounding - Lt4',
    location: 'Lantai 4',
    lastCleaned: daysAgo(4),
    nextCleaning: daysFrom(3),
    checklistStatus: null,
    status: 'overdue',
    hasRecord: false,
    reportApproved: false,
  },
  {
    id: 'K1R-2',
    machineName: 'K1R2',
    machineType: 'K1R',
    subLabel: 'Compounding - Lt3',
    location: 'Lantai 3',
    lastCleaned: daysAgo(60),
    nextCleaning: daysFrom(-48),
    checklistStatus: 'pending',
    status: 'changeover',
    hasRecord: true,
    reportApproved: false,
  },
  {
    id: 'K1R-3',
    machineName: 'K1R3',
    machineType: 'K1R',
    subLabel: 'Compounding - Lt3',
    location: 'Lantai 3',
    lastCleaned: daysAgo(55),
    nextCleaning: daysFrom(-43),
    checklistStatus: 'pending',
    status: 'qa',
    hasRecord: true,
    reportApproved: false,
  },
  {
    id: 'MF-1',
    machineName: 'MF 1',
    machineType: 'MF',
    subLabel: 'Filing - Lt1',
    location: 'Lantai 1',
    lastCleaned: daysAgo(90),
    nextCleaning: daysFrom(-55),
    checklistStatus: 'pending',
    status: 'qa',
    hasRecord: true,
    reportApproved: false,
  },
  {
    id: 'K1R-5',
    machineName: 'K1R5',
    machineType: 'K1R',
    subLabel: 'Compounding - Lt3',
    location: 'Lantai 3',
    lastCleaned: daysAgo(30),
    nextCleaning: daysFrom(5),
    checklistStatus: 'approved',
    status: 'safe',
    hasRecord: true,
    reportApproved: true,
  },
  {
    id: 'RVS-P',
    machineName: 'RVS P',
    machineType: 'RVS',
    subLabel: 'Filing - Lt1',
    location: 'Lantai 1',
    lastCleaned: daysAgo(2),
    nextCleaning: daysFrom(33),
    checklistStatus: 'pending',
    status: 'inprogress',
    hasRecord: true,
    reportApproved: false,
  },
];
